repositories:
  - name: argo
    url: https://argoproj.github.io/argo-helm
  - name: prometeheus-community
    url: https://prometheus-community.github.io/helm-charts

releases:
  - name: argocd
    namespace: argocd
    chart: argo/argo-cd
    version: 8.3.3
    values:
      - values/argocd-values.yaml

  # # 初回はhelmfile syncを実行する。helmfile apply だとCRDが作成されずエラーになる。
  # - name: kube-prometheus-stack
  #   namespace: monitoring
  #   chart: prometheus-community/kube-prometheus-stack
  #   version: 77.5.0
  #   values:
  #     - values/prometheus.yaml
  #     - values/grafana.yaml
