volumes:
  db-data:

services:
  web:
    build: ../api
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - ../api:/api
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=user
    ports:
      - "3000:3000"
    depends_on:
      - db
    links:
      - db

  db:
    image: postgres:12
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=user
      - POSTGRES_DB=myapi_development

  frontend:
    build: ../frontend
    command: npm run dev
    volumes:
      - ../frontend:/frontend
      - /frontend/node_modules
    ports:
      - "3001:3001"
    working_dir: /frontend
    depends_on:
      - web
