volumes:
  db-data:

services:
  api:
    build: ../api
    ports:
      - "8080:8080"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=user
      - POSTGRES_DB=myapi_development
      - POSTGRES_HOST=db
    depends_on:
      - db
    links:
      - db
  db:
    image: postgres:12
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=user
      - POSTGRES_DB=myapi_development


  frontend:
    build: ../frontend
    command: npm run dev
    volumes:
      - ../frontend:/frontend
      - /frontend/node_modules
    ports:
      - "3001:3001"
    working_dir: /frontend
    depends_on:
      - api
